### ISSUE TITLE
daplink_v2.ino

### ISSUE THREAD

**Issue by jmg5150** [Seeed-Studio/Seeed_Arduino_DAPLink#8]
When running the daplink_v2.ino example, Windows 10 does not find a driver to use with the adapter. See my screenshot below. My understanding is that DAPLink V2 should use WinUSB driver, however it doesn't seem like the WCID for WinUSB is included in the USB descriptors to facilitate the automatic association with the driver.

Furthermore, when I force WinUSB driver (v6.1.7600.16385) to be associated with the device using Zadig, it still cannot be discovered by pyOCD or other tools.

Can you either provide additional details necessary to getting the daplink_v2.ino firmware to work with Windows or help to identify what might be causing this? I've spent a bit of time debugging myself but haven't been able to find the source of the problem.

Note that the simple_daplink.ino example is working fine, no driver issues, and can easily be discovered by pyOCD and used within my toolchains.

**Screenshots**
Windows Device Manager upon device plug-in:
![device-manager-daplink-v2](https://user-images.githubusercontent.com/5467905/107719344-db930a00-6c8c-11eb-9e37-9a73427c03fc.png)
Zadig doesn't see the WCID descriptor or driver either:
![image](https://user-images.githubusercontent.com/5467905/107721489-a0470a00-6c91-11eb-88d9-8b2e6cd897ed.png)

Thanks!

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/Seeed_Arduino_DAPLink/tree/master/examples/simple_daplink @jmg5150 this sketch work?

**Comment by ciniml** [comment]
Currently it's difficult to implement WCID because the Adafruit TinyUSB library does not support returning arbitrary index string descriptor, nor returning arbitrary descriptors, those are necessary to return OS string descriptor whose index is 0xee.

In order to that, at first, we have to modify the Adafruit TinyUSB to support arbitrary index string descriptor.
Then we also have to modify the library to support returning arbitrary descriptors to return Microsoft Compatible ID Feature Descriptor.

I think it's not so difficult in the technological perspective, but it takes some time to do that.

So at this time, the easiest solution is, install the WinUSB driver with Zadig, I think.

**Comment by jmg5150** [comment]
Thanks for the comments on this. In the time since my post, I was able to investigate this issue a bit further, and I saw exactly what @ciniml pointed out regarding implementing WCID. The current structure of the TinyUSB library makes it very difficult to implement. Although I see that the Adafruit WebUSB example is able to implement the correct descriptors to allow for WCID to automatically use WinUSB driver. Unfortunately I didn't have enough to time to justify making a big change to the library to expose this, so I just used Zadig to manually set the driver. Once I manually set the driver, the daplink_v2.ino sketch works well with pyOCD.

Is there any more active development on this project planned, or is this pretty much it's final state? I'm personally very interested in the following three features from the original DAPLink project and would be willing to help contribute:
-- mass storage device for drag-n-drop programming (based on comments in the code, seems that this is already planned for)
-- WebUSB support (to use with https://github.com/ARMmbed/dapjs) 
-- and WCID for correct driver detection on Windows (but is challenging due to items discussed above)

Any insight as to any planned work would be greatly appreciated. Thanks!

**Comment by aktoey** [comment]
arduino ide error 

Arduino:1.8.15 (Windows 10), 开发板："LilyPad Arduino USB"





















simple_daplink:58:19: error: cannot declare variable 'usb_hid' to be of abstract type 'Adafruit_USBD_HID'

 Adafruit_USBD_HID usb_hid;

                   ^~~~~~~

In file included from C:\Users\cheng\Documents\Arduino\libraries\Adafruit_TinyUSB_Arduino-master\src/Adafruit_TinyUSB.h:40:0,

                 from C:\Users\cheng\AppData\Local\Temp\arduino_modified_sketch_15759\simple_daplink.ino:46:

C:\Users\cheng\Documents\Arduino\libraries\Adafruit_TinyUSB_Arduino-master\src/arduino/hid/Adafruit_USBD_HID.h:30:7: note:   because the following virtual functions are pure within 'Adafruit_USBD_HID':

 class Adafruit_USBD_HID : public Adafruit_USBD_Interface {

       ^~~~~~~~~~~~~~~~~

In file included from C:\Users\cheng\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.1\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/Adafruit_TinyUSB_Core.h:35:0,

                 from C:\Users\cheng\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.1\cores\arduino/Arduino.h:171,

                 from sketch\simple_daplink.ino.cpp:1:

C:\Users\cheng\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.1\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/Adafruit_USBD_Device.h:38:22: note: 	virtual uint16_t Adafruit_USBD_Interface::getDescriptor(uint8_t, uint8_t*, uint16_t)

     virtual uint16_t getDescriptor(uint8_t itfnum, uint8_t* buf, uint16_t bufsize) = 0;

                      ^~~~~~~~~~~~~

exit status 1

cannot declare variable 'usb_hid' to be of abstract type 'Adafruit_USBD_HID'

**Comment by aktoey** [comment]
please thank you

**Comment by Pillar1989** [comment]
`"LilyPad Arduino USB` ?  @aktoey

**Comment by aktoey** [comment]
seeeduino xiao

**Comment by aktoey** [comment]
我现在没有板子，只是先编译程序，板子在买了，但是编译都不通过

**Comment by aktoey** [comment]
我按照seeed里面如何用arduino制作一个daplink的教程一步一步完成的，

**Comment by ciniml** [comment]
I've confirmed that there is compilation issue with the latest Adafruit TinyUSB Library.
In order to build this firmware, you have to use Adafruit TinyUSB Library 0.10.5.

Maybe there are some API changes which is no backward compatibility from 0.10.5 to 1.0.0.

By the way, this issue is about the DAPLink V2 WCID problem and your problem seems not related to this. So I think you should post another issue for your problem.

**Comment by aktoey** [comment]
yes , i succeed.if i want to use the laster Tinyusb Library ,what should i do?

**Comment by ciniml** [comment]
you can modify the sourcecode to support the latest Adafruit library if you want to use the latest  library before the sourcecode is updeted by original author.

I have no idea about how much time it takes to modify the code, since i have not confirmed which changes are affecting the compilation problem.

**Comment by aktoey** [comment]
thanks for your suggestion

**Comment by ciniml** [comment]
With further investigation, I've found that this is caused by the change of the structure of Adafruit_TinyUSB_Arduino from version 1.0.0.
Adafruit moved all sources from Adafruit_TinyUSB_ArduinoCore to Adafruit_TinyUSB_Arduino, which is previously contained by their Arduino core.

So, in order to use the latest Adafruit_TinyUSB_Arduino with Seeed's boards, the Arduino core maintained by Seeed must be fixed to support the new Adafruit_TinyUSB_Arduino by Seeed.

**Comment by Pillar1989** [comment]
Thanks for the analysis, but we don't have the energy to maintain the arduino core at the moment. it won't be updated soon. PR is very welcome and we all come together to finish it.
